`timescale 1ns/1ps

module tb_top;
    // =====================================================
    // 1. PARAMETERS (Parsed by opcode_gen.py)
    // =====================================================
    // These must follow this exact format for the Python script to detect them.
    parameter LEN_X = 4;  // Length of input x[n]
    parameter LEN_Y = 10; // Total length of y[n]
    
    // Calculated target length for h[n]
    localparam LEN_H = LEN_Y - LEN_X + 1; 

    // =====================================================
    // 2. SIGNALS & STORAGE
    // =====================================================
    reg clk, rst;
    reg [9:0] pc;              // 10-bit PC for >256 instructions
    wire [7:0] instr;
    wire [255:0] cycle_count;
    
    // Arrays for verification
    reg [7:0]  expected_h [0:LEN_H-1];
    reg [15:0] temp_y;
    reg [31:0] running_sum;
    integer i, j, error_count;

    // =====================================================
    // 3. COMPONENT INSTANTIATION
    // =====================================================
    
    // Instruction RAM: Loads 'program.mem' generated by your script
    instr_ram #(.DEPTH(1024), .ADDR_WIDTH(10)) u_instr_ram (
        .clk(clk), .pc(pc), .instr_out(instr)
    );

    // Your Top-Level Design (Limited to 4 general-purpose registers)
    top u_top (
        .clk(clk), .rst(rst), .instr(instr), .cycle_count(cycle_count)
    );

    // =====================================================
    // 4. CLOCK GENERATION (100MHz)
    // =====================================================
    always #5 clk = ~clk;

    // =====================================================
    // 5. MAIN SIMULATION BLOCK
    // =====================================================
    initial begin
        // Initialize
        clk = 0; rst = 1; pc = 0; error_count = 0;
        
        // -------------------------------------------------
        // STEP A: PRE-LOAD DATA RAM
        // -------------------------------------------------
        
        // x[n] = {5, 2, 1, 0}
        u_top.u_ram.mem[0] = 8'd5; 
        u_top.u_ram.mem[1] = 8'd2; 
        u_top.u_ram.mem[2] = 8'd1; 
        u_top.u_ram.mem[3] = 8'd0; 

        // y[n] = {100, 240, 450, 600, 350, 150, 80, 40, 20, 10}
        // Stored as 16-bit [High Byte, Low Byte] in Sector 2 (Addresses 64+)
        for (i = 0; i < LEN_Y; i = i + 1) begin
            case(i)
                0: begin u_top.u_ram.mem[64+2*i]=8'h00; u_top.u_ram.mem[65+2*i]=8'd100; end
                1: begin u_top.u_ram.mem[64+2*i]=8'h00; u_top.u_ram.mem[65+2*i]=8'd240; end
                2: begin u_top.u_ram.mem[64+2*i]=8'h01; u_top.u_ram.mem[65+2*i]=8'hC2;  end // 450
                3: begin u_top.u_ram.mem[64+2*i]=8'h02; u_top.u_ram.mem[65+2*i]=8'h58;  end // 600
                4: begin u_top.u_ram.mem[64+2*i]=8'h01; u_top.u_ram.mem[65+2*i]=8'h5E;  end // 350
                5: begin u_top.u_ram.mem[64+2*i]=8'h00; u_top.u_ram.mem[65+2*i]=8'd150; end
                6: begin u_top.u_ram.mem[64+2*i]=8'h00; u_top.u_ram.mem[65+2*i]=8'd80;  end
                7: begin u_top.u_ram.mem[64+2*i]=8'h00; u_top.u_ram.mem[65+2*i]=8'd40;  end
                8: begin u_top.u_ram.mem[64+2*i]=8'h00; u_top.u_ram.mem[65+2*i]=8'd20;  end
                9: begin u_top.u_ram.mem[64+2*i]=8'h00; u_top.u_ram.mem[65+2*i]=8'd10;  end
            endcase
        end
        
        // Clear Output RAM Sector 3 (Addresses 128+)
        for (i = 128; i < 256; i = i + 1) u_top.u_ram.mem[i] = 8'd0;

        // -------------------------------------------------
        // STEP B: GOLDEN MODEL (Verilog Expected Values)
        // -------------------------------------------------
        // This calculates h[n] = (y[n] - sum(h[n-j]*x[j])) / x[0]
        for (i = 0; i < LEN_H; i = i + 1) begin
            temp_y = {u_top.u_ram.mem[64 + 2*i], u_top.u_ram.mem[65 + 2*i]};
            running_sum = 0;
            for (j = 1; j <= i && j < LEN_X; j = j + 1) begin
                running_sum = running_sum + (expected_h[i-j] * u_top.u_ram.mem[j]);
            end
            expected_h[i] = (temp_y > running_sum) ? (temp_y - running_sum) / u_top.u_ram.mem[0] : 0;
        end

        // -------------------------------------------------
        // STEP C: EXECUTION PHASE
        // -------------------------------------------------
        #20 rst = 0; // Start the CPU
        
        // Wait for the hardware HLT signal
        wait(u_top.dec.hlt_en);
        #10; 

        // -------------------------------------------------
        // STEP D: FINAL VERIFICATION REPORT
        // -------------------------------------------------
        $display("\n====================================================");
        $display("   BIT-TRIX 2026: ACTUAL vs EXPECTED REPORT");
        $display("====================================================");
        $display("Total Efficiency: %0d Cycles", cycle_count); //
        $display("Configuration: Lx=%0d, Ly=%0d, Target Lh=%0d", LEN_X, LEN_Y, LEN_H);
        $display("----------------------------------------------------");
        $display(" INDEX |  ACTUAL  | EXPECTED | STATUS");
        $display("-------|----------|----------|----------------------");

        for (i = 0; i < LEN_H; i = i + 1) begin
            if (u_top.u_ram.mem[128 + i] === expected_h[i]) begin
                $display(" h[%0d]  |   %3d    |   %3d    | [MATCH]", i, u_top.u_ram.mem[128+i], expected_h[i]);
            end else begin
                $display(" h[%0d]  |   %3d    |   %3d    | [!!! MISMATCH !!!]", i, u_top.u_ram.mem[128+i], expected_h[i]);
                error_count = error_count + 1;
            end
        end

        $display("----------------------------------------------------");
        if (error_count == 0)
            $display(" RESULT: PASSED - System is mathematically correct.");
        else
            $display(" RESULT: FAILED - %0d mismatches found.", error_count);
        $display("====================================================\n");
        
        $finish;
    end

    // PC Control Logic
    always @(posedge clk) begin
        if (rst) pc <= 0;
        else if (!u_top.dec.hlt_en) pc <= pc + 1;
    end

endmodule