`timescale 1ns/1ps
module instr_ram #(
    parameter DEPTH      = 1024,
    parameter ADDR_WIDTH = 10
)(
    input clk,
    input [ADDR_WIDTH-1:0] pc,       // program counter as address
    output reg [7:0] instr_out       // fetched instruction
);
    reg [7:0] mem [0:DEPTH-1];
 
    // Load program from file generated by opcode_gen.py
    initial begin
        $readmemb("program.mem", mem);
    end
 
    // Fetch instruction at PC every cycle
    always @(posedge clk) begin
        instr_out <= mem[pc];
    end
 
endmodule